# environment params
DEFAULT_ACTION = 0
HOLD_INTERVALS = 60
IMPOSED_DELAY_LIMIT = 240

# training params
N_EPISODES_TRAIN = 10
TIMESTEPS = 10000

EARLY_DEP_LIMIT_SEC = 180
NR_ACTIONS_D_RL = int((IMPOSED_DELAY_LIMIT+EARLY_DEP_LIMIT_SEC)/HOLD_INTERVALS) + 1

# Hyperparameters
